#if UNITY_EDITOR
using System;
using System.Globalization;
using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace RSWebGLLandscape.Editor
{
    /// <summary>
    /// After a WebGL build, writes the chosen template settings into
    /// <c>&lt;build&gt;/TemplateData/rsconfig.js</c> so the RSLandscape
    /// <c>index.html</c> picks them up via <c>window.RSConfigOverride</c>.
    /// Only touches builds whose <c>index.html</c> actually references that
    /// override (i.e. builds using this template), so other templates are safe.
    /// </summary>
    class RSWebGLTemplateBuildProcessor : IPostprocessBuildWithReport
    {
        public int callbackOrder => 0;

        public void OnPostprocessBuild(BuildReport report)
        {
            if (report.summary.platform != BuildTarget.WebGL) return;

            string outDir = report.summary.outputPath;
            if (string.IsNullOrEmpty(outDir)) return;

            string indexPath = Path.Combine(outDir, "index.html");
            if (!File.Exists(indexPath)) return;

            // Guard: only patch builds that use the RSLandscape template.
            if (File.ReadAllText(indexPath).IndexOf("RSConfigOverride", StringComparison.Ordinal) < 0)
                return;

            var s = RSWebGLTemplateSettings.GetOrCreate();
            string dir = Path.Combine(outDir, "TemplateData");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, "rsconfig.js"), BuildJs(s));
        }

        static string BuildJs(RSWebGLTemplateSettings s)
        {
            string fit = s.fitMode.ToString().ToLowerInvariant();
            string bg = "#" + ColorUtility.ToHtmlStringRGB(s.background);
            string dpr = s.maxDevicePixelRatio.ToString(CultureInfo.InvariantCulture);

            return
                "// Generated by RS WebGL Landscape (Project Settings > RS WebGL Landscape).\n" +
                "// Edit those settings and rebuild; manual changes here are overwritten on build.\n" +
                "window.RSConfigOverride = {\n" +
                "  fitMode: \"" + fit + "\",\n" +
                "  aspectW: " + s.aspectWidth.ToString(CultureInfo.InvariantCulture) + ",\n" +
                "  aspectH: " + s.aspectHeight.ToString(CultureInfo.InvariantCulture) + ",\n" +
                "  background: \"" + bg + "\",\n" +
                "  maxDevicePixelRatio: " + dpr + "\n" +
                "};\n";
        }
    }
}
#endif
